### ISSUE TITLE
Improve v11 release information

### ISSUE THREAD

**Issue by eduardojmatos** [getninjas/gaiden#108]
We need to improve documentation about major release 11 https://github.com/getninjas/gaiden/releases/tag/v11.0.0 :)

**Comment by iondrimba** [comment]
@eduardojmatos Did a small update on the release documentation. Do you think is too much?
https://github.com/getninjas/gaiden/releases/tag/v11.0.0

**Comment by eduardojmatos** [comment]
@iondrimba awesome! Now we have a respectable and very descriptive release notes!!!! Nice!!
