### ISSUE TITLE
[BUG] Broken documentation

### ISSUE THREAD

**Issue by iondrimba** [getninjas/gaiden#174]
I was trying to show this project to some people but some files are not being found.
I tried to fix it locally but did not succeed.

![Annotation 2019-08-06 224923](https://user-images.githubusercontent.com/178548/62588583-9f633a00-b89c-11e9-804f-0b0cac7ec5a2.png)

![Annotation 2019-08-06 224716](https://user-images.githubusercontent.com/178548/62588578-98d4c280-b89c-11e9-9f85-cd1a94bf024c.png)

**Comment by williamcosta** [comment]
It may have been after we implemented the themes in Gaiden, let's see this here, thanks for reporting the bug @iondrimba
