### ISSUE TITLE
Update browser support list

### ISSUE THREAD

**Issue by eduardojmatos** [getninjas/gaiden#50]
On the last 3 months, the visits from Internet Explorer 9 dropped considerably.

- [x] Decrease browserSupport constant on `./bin/build/prod/css`;
- [ ] Re-visit our `no-flexbox` classes on components (old Android browsers still continue accessing our site);
- [ ] Add support info on our README.

**Comment by felipeorlando** [comment]
Documentation is the keyword of our workflow. We need this now. 😆

**Comment by eduardojmatos** [comment]
@felipeorlando more one issue outdated. We are supporting IE9 because this make sense to our business yet
