### ISSUE TITLE
Create form components

### ISSUE THREAD

**Issue by eduardojmatos** [getninjas/gaiden#51]
Create a form and fields components are our next job in Gaiden project. So, the following items needs to be done:

- [ ] Basic structure of a form;
- [ ] `legend` and `fieldset` elements;
- [ ] `field` element, to wrap `label` and `input`;
- [ ] `label`, `input`, `select`, `radio`, `checkbox`, `toggle` elements;
- [ ] messages of validation (`mesage`, `message--success`, `message--error`, etc.);
- [ ] `disable` option of elements;
- [ ] general message element;
- [ ] footer with steps (that can be or not a part of `form` element - we can discuss about this).

**Comment by felipeorlando** [comment]
With the new form generator, we could priorize this... 🤔

**Comment by eduardojmatos** [comment]
@felipeorlando some of this items are completed. This issue seems to be outdated...
