### ISSUE TITLE
Automatizar inclusão de vendor-prefix para propriedades do CSS mais modernas

### ISSUE THREAD

**Issue by iondrimba** [getninjas/gaiden#77]
Estou realizando vários testes no BrowserStack, e percebi que na página de categorias no iOS (iPad/iPhone) o layout tem apresentado algumas quebras. Investigando o código, reparei que em alguns casos o problema é apenas a falta do vendorprefix.

Isso acontece apenas em versões anteriores ao iOS9.
De qualquer maneira, acho que seria interessante ter essa task de autoprefix, assim a gente lima de vez qualquer possibilidade de bug nesse sentido.

@eduardojmatos @MarcoBrunoBR @bsoares @Eliada

**Comment by eduardojmatos** [comment]
@iondrimba estamos usando o cssnano, que já tem o autoprefixer. Acho que a questão é usarmos um json/csv com todos os browsers que queremos suportar. O Daniel já fez isso pra gente (gerar o CSV), agora só falta adicionar no nosso build [e não usarmos essa string aqui](https://github.com/getninjas/gaiden/blob/master/bin/build/prod/css.js#L8)
